// Docs: https://www.instantdb.com/docs/permissions

import type { InstantRules } from "@instantdb/core";

const rules = {
  attrs: {
    allow: {
      $default: "false",
    },
  },
  $files: {
    bind: [
      "isAuthenticated",
      "auth.id != null",
      "isGuest",
      "auth.isGuest == true",
      "isNotGuest",
      "auth.isGuest == false",
      "isOwner",
      "data.owner == auth.id || auth.id == data.user || auth.id == data.id ",
      "isStillOwner",
      "auth.id == newData.owner || auth.id == newData.user || auth.id == newData.id ",
      "isPremium",
      "auth.ref('$user.profile.plan').exists(p, p in ['basic', 'plus', 'pro'])",
      "isTeacher",
      "auth.id in data.ref('classTeachers.id')",
      "isStillTeacher",
      "auth.id in newData.ref('classTeachers.id')",
      "isOrgMember",
      "auth.id in data.ref('orgStudents.id') || auth.id in data.ref('orgTeachers.id') || auth.id in data.ref('orgParents.id')",
      "isStillOrgMember",
      "auth.id in newData.ref('orgStudents.id') || auth.id in newData.ref('orgTeachers.id') || auth.id in newData.ref('orgParents.id')",
      "isClassMember",
      "auth.id in data.ref('classStudents.id') || auth.id in data.ref('classTeachers.id') || auth.id in data.ref('classParents.id')",
      "isStillClassMember",
      "auth.id in newData.ref('classStudents.id') || auth.id in newData.ref('classTeachers.id') || auth.id in newData.ref('classParents.id')",
      "isClassParent",
      "auth.id in data.ref('classParents.id')",
      "isStillClassParent",
      "auth.id in newData.ref('classParents.id')",
      "isAdmin",
      "auth.id in data.ref('admins.id')",
      "isStillAdmin",
      "auth.id in newData.ref('admins.id')",
      "isClassAdmin",
      "auth.id in data.ref('classAdmins.id')",
      "isStillClassAdmin",
      "auth.id in newData.ref('classAdmins.id')",
    ],
    allow: {
      view: "isAuthenticated && isOwner",
      create: "isAuthenticated",
      delete: "isAuthenticated && isOwner",
      update:
        "isAuthenticated && (data.ref('owner.id') == [] || (isOwner && isStillOwner))",
    },
  },
  $users: {
    bind: [
      "isAuthenticated",
      "auth.id != null",
      "isGuest",
      "auth.isGuest == true",
      "isNotGuest",
      "auth.isGuest == false",
      "isOwner",
      "data.owner == auth.id || auth.id == data.user || auth.id == data.id ",
      "isStillOwner",
      "auth.id == newData.owner || auth.id == newData.user || auth.id == newData.id ",
      "isPremium",
      "auth.ref('$user.profile.plan').exists(p, p in ['basic', 'plus', 'pro'])",
      "isTeacher",
      "auth.id in data.ref('classTeachers.id')",
      "isStillTeacher",
      "auth.id in newData.ref('classTeachers.id')",
      "isOrgMember",
      "auth.id in data.ref('orgStudents.id') || auth.id in data.ref('orgTeachers.id') || auth.id in data.ref('orgParents.id')",
      "isStillOrgMember",
      "auth.id in newData.ref('orgStudents.id') || auth.id in newData.ref('orgTeachers.id') || auth.id in newData.ref('orgParents.id')",
      "isClassMember",
      "auth.id in data.ref('classStudents.id') || auth.id in data.ref('classTeachers.id') || auth.id in data.ref('classParents.id')",
      "isStillClassMember",
      "auth.id in newData.ref('classStudents.id') || auth.id in newData.ref('classTeachers.id') || auth.id in newData.ref('classParents.id')",
      "isClassParent",
      "auth.id in data.ref('classParents.id')",
      "isStillClassParent",
      "auth.id in newData.ref('classParents.id')",
      "isAdmin",
      "auth.id in data.ref('admins.id')",
      "isStillAdmin",
      "auth.id in newData.ref('admins.id')",
      "isClassAdmin",
      "auth.id in data.ref('classAdmins.id')",
      "isStillClassAdmin",
      "auth.id in newData.ref('classAdmins.id')",
    ],
    allow: {
      view: "isAuthenticated",
      create: "false",
      delete: "false",
      update:
        "isAuthenticated && ((isOwner && isStillOwner) || (auth.id in data.ref('studentClasses.classAdmins.id') || auth.id in data.ref('parentClasses.classAdmins.id') || auth.id in data.ref('teacherClasses.classAdmins.id') || auth.id in data.ref('studentOrganizations.admins.id') || auth.id in data.ref('parentOrganizations.admins.id') || auth.id in data.ref('teacherOrganizations.admins.id')))",
    },
  },
  classes: {
    bind: [
      "isAuthenticated",
      "auth.id != null",
      "isGuest",
      "auth.isGuest == true",
      "isNotGuest",
      "auth.isGuest == false",
      "isOwner",
      "data.owner == auth.id || auth.id == data.user || auth.id == data.id ",
      "isStillOwner",
      "auth.id == newData.owner || auth.id == newData.user || auth.id == newData.id ",
      "isPremium",
      "auth.ref('$user.profile.plan').exists(p, p in ['basic', 'plus', 'pro'])",
      "isTeacher",
      "auth.id in data.ref('classTeachers.id')",
      "isStillTeacher",
      "auth.id in newData.ref('classTeachers.id')",
      "isOrgMember",
      "auth.id in data.ref('orgStudents.id') || auth.id in data.ref('orgTeachers.id') || auth.id in data.ref('orgParents.id')",
      "isStillOrgMember",
      "auth.id in newData.ref('orgStudents.id') || auth.id in newData.ref('orgTeachers.id') || auth.id in newData.ref('orgParents.id')",
      "isClassMember",
      "auth.id in data.ref('classStudents.id') || auth.id in data.ref('classTeachers.id') || auth.id in data.ref('classParents.id')",
      "isStillClassMember",
      "auth.id in newData.ref('classStudents.id') || auth.id in newData.ref('classTeachers.id') || auth.id in newData.ref('classParents.id')",
      "isClassParent",
      "auth.id in data.ref('classParents.id')",
      "isStillClassParent",
      "auth.id in newData.ref('classParents.id')",
      "isAdmin",
      "auth.id in data.ref('admins.id')",
      "isStillAdmin",
      "auth.id in newData.ref('admins.id')",
      "isClassAdmin",
      "auth.id in data.ref('classAdmins.id')",
      "isStillClassAdmin",
      "auth.id in newData.ref('classAdmins.id')",
    ],
    allow: {
      view: "isAuthenticated && (isOwner || isClassAdmin || isClassMember || isClassParent)",
      create: "isAuthenticated",
      delete: "isAuthenticated && isOwner",
      update:
        "isAuthenticated && (isOwner || isClassAdmin) && (isStillOwner || isStillClassAdmin)",
    },
  },
  joinTokens: {
    bind: [
      "isAuthenticated",
      "auth.id != null",
      "isGuest",
      "auth.isGuest == true",
      "isNotGuest",
      "auth.isGuest == false",
      "isOwner",
      "data.owner == auth.id || auth.id == data.user || auth.id == data.id ",
      "isStillOwner",
      "auth.id == newData.owner || auth.id == newData.user || auth.id == newData.id ",
      "isPremium",
      "auth.ref('$user.profile.plan').exists(p, p in ['basic', 'plus', 'pro'])",
      "isTeacher",
      "auth.id in data.ref('classTeachers.id')",
      "isStillTeacher",
      "auth.id in newData.ref('classTeachers.id')",
      "isOrgMember",
      "auth.id in data.ref('orgStudents.id') || auth.id in data.ref('orgTeachers.id') || auth.id in data.ref('orgParents.id')",
      "isStillOrgMember",
      "auth.id in newData.ref('orgStudents.id') || auth.id in newData.ref('orgTeachers.id') || auth.id in newData.ref('orgParents.id')",
      "isClassMember",
      "auth.id in data.ref('classStudents.id') || auth.id in data.ref('classTeachers.id') || auth.id in data.ref('classParents.id')",
      "isStillClassMember",
      "auth.id in newData.ref('classStudents.id') || auth.id in newData.ref('classTeachers.id') || auth.id in newData.ref('classParents.id')",
      "isClassParent",
      "auth.id in data.ref('classParents.id')",
      "isStillClassParent",
      "auth.id in newData.ref('classParents.id')",
      "isAdmin",
      "auth.id in data.ref('admins.id')",
      "isStillAdmin",
      "auth.id in newData.ref('admins.id')",
      "isClassAdmin",
      "auth.id in data.ref('classAdmins.id')",
      "isStillClassAdmin",
      "auth.id in newData.ref('classAdmins.id')",
    ],
    allow: {
      view: "isAuthenticated && isOwner",
      create: "false",
      delete: "false",
      update: "false",
    },
  },
  orgJoinCodes: {
    bind: [
      "isAuthenticated",
      "auth.id != null",
      "isGuest",
      "auth.isGuest == true",
      "isNotGuest",
      "auth.isGuest == false",
      "isOwner",
      "data.owner == auth.id || auth.id == data.user || auth.id == data.id ",
      "isStillOwner",
      "auth.id == newData.owner || auth.id == newData.user || auth.id == newData.id ",
      "isPremium",
      "auth.ref('$user.profile.plan').exists(p, p in ['basic', 'plus', 'pro'])",
      "isTeacher",
      "auth.id in data.ref('classTeachers.id')",
      "isStillTeacher",
      "auth.id in newData.ref('classTeachers.id')",
      "isOrgMember",
      "auth.id in data.ref('orgStudents.id') || auth.id in data.ref('orgTeachers.id') || auth.id in data.ref('orgParents.id')",
      "isStillOrgMember",
      "auth.id in newData.ref('orgStudents.id') || auth.id in newData.ref('orgTeachers.id') || auth.id in newData.ref('orgParents.id')",
      "isClassMember",
      "auth.id in data.ref('classStudents.id') || auth.id in data.ref('classTeachers.id') || auth.id in data.ref('classParents.id')",
      "isStillClassMember",
      "auth.id in newData.ref('classStudents.id') || auth.id in newData.ref('classTeachers.id') || auth.id in newData.ref('classParents.id')",
      "isClassParent",
      "auth.id in data.ref('classParents.id')",
      "isStillClassParent",
      "auth.id in newData.ref('classParents.id')",
      "isAdmin",
      "auth.id in data.ref('admins.id')",
      "isStillAdmin",
      "auth.id in newData.ref('admins.id')",
      "isClassAdmin",
      "auth.id in data.ref('classAdmins.id')",
      "isStillClassAdmin",
      "auth.id in newData.ref('classAdmins.id')",
    ],
    allow: {
      view: "isAuthenticated && (auth.id in data.ref('organization.owner.id') || auth.id in data.ref('organization.admins.id'))",
      create: "isAuthenticated",
      delete:
        "isAuthenticated && (auth.id in data.ref('organization.owner.id') || auth.id in data.ref('organization.admins.id'))",
      update:
        "isAuthenticated && (auth.id in data.ref('organization.owner.id') || auth.id in data.ref('organization.admins.id'))",
    },
  },
  organizations: {
    bind: [
      "isAuthenticated",
      "auth.id != null",
      "isGuest",
      "auth.isGuest == true",
      "isNotGuest",
      "auth.isGuest == false",
      "isOwner",
      "data.owner == auth.id || auth.id == data.user || auth.id == data.id ",
      "isStillOwner",
      "auth.id == newData.owner || auth.id == newData.user || auth.id == newData.id ",
      "isPremium",
      "auth.ref('$user.profile.plan').exists(p, p in ['basic', 'plus', 'pro'])",
      "isTeacher",
      "auth.id in data.ref('classTeachers.id')",
      "isStillTeacher",
      "auth.id in newData.ref('classTeachers.id')",
      "isOrgMember",
      "auth.id in data.ref('orgStudents.id') || auth.id in data.ref('orgTeachers.id') || auth.id in data.ref('orgParents.id')",
      "isStillOrgMember",
      "auth.id in newData.ref('orgStudents.id') || auth.id in newData.ref('orgTeachers.id') || auth.id in newData.ref('orgParents.id')",
      "isClassMember",
      "auth.id in data.ref('classStudents.id') || auth.id in data.ref('classTeachers.id') || auth.id in data.ref('classParents.id')",
      "isStillClassMember",
      "auth.id in newData.ref('classStudents.id') || auth.id in newData.ref('classTeachers.id') || auth.id in newData.ref('classParents.id')",
      "isClassParent",
      "auth.id in data.ref('classParents.id')",
      "isStillClassParent",
      "auth.id in newData.ref('classParents.id')",
      "isAdmin",
      "auth.id in data.ref('admins.id')",
      "isStillAdmin",
      "auth.id in newData.ref('admins.id')",
      "isClassAdmin",
      "auth.id in data.ref('classAdmins.id')",
      "isStillClassAdmin",
      "auth.id in newData.ref('classAdmins.id')",
    ],
    allow: {
      view: "isAuthenticated && (isOwner || isAdmin || isOrgMember)",
      create: "isAuthenticated",
      delete: "isAuthenticated && isOwner",
      update:
        "isAuthenticated && (isOwner || isAdmin) && (isStillOwner || isStillAdmin)",
    },
  },
  classJoinCodes: {
    bind: [
      "isAuthenticated",
      "auth.id != null",
      "isGuest",
      "auth.isGuest == true",
      "isNotGuest",
      "auth.isGuest == false",
      "isOwner",
      "data.owner == auth.id || auth.id == data.user || auth.id == data.id ",
      "isStillOwner",
      "auth.id == newData.owner || auth.id == newData.user || auth.id == newData.id ",
      "isPremium",
      "auth.ref('$user.profile.plan').exists(p, p in ['basic', 'plus', 'pro'])",
      "isTeacher",
      "auth.id in data.ref('classTeachers.id')",
      "isStillTeacher",
      "auth.id in newData.ref('classTeachers.id')",
      "isOrgMember",
      "auth.id in data.ref('orgStudents.id') || auth.id in data.ref('orgTeachers.id') || auth.id in data.ref('orgParents.id')",
      "isStillOrgMember",
      "auth.id in newData.ref('orgStudents.id') || auth.id in newData.ref('orgTeachers.id') || auth.id in newData.ref('orgParents.id')",
      "isClassMember",
      "auth.id in data.ref('classStudents.id') || auth.id in data.ref('classTeachers.id') || auth.id in data.ref('classParents.id')",
      "isStillClassMember",
      "auth.id in newData.ref('classStudents.id') || auth.id in newData.ref('classTeachers.id') || auth.id in newData.ref('classParents.id')",
      "isClassParent",
      "auth.id in data.ref('classParents.id')",
      "isStillClassParent",
      "auth.id in newData.ref('classParents.id')",
      "isAdmin",
      "auth.id in data.ref('admins.id')",
      "isStillAdmin",
      "auth.id in newData.ref('admins.id')",
      "isClassAdmin",
      "auth.id in data.ref('classAdmins.id')",
      "isStillClassAdmin",
      "auth.id in newData.ref('classAdmins.id')",
    ],
    allow: {
      view: "isAuthenticated && (auth.id in data.ref('class.owner.id') || auth.id in data.ref('class.classAdmins.id') || auth.id in data.ref('class.organization.owner.id') || auth.id in data.ref('class.organization.admins.id') || auth.id in data.ref('class.classTeachers.id'))",
      create: "isAuthenticated",
      delete:
        "isAuthenticated && (auth.id in data.ref('class.owner.id') || auth.id in data.ref('class.classAdmins.id') || auth.id in data.ref('class.organization.owner.id') || auth.id in data.ref('class.organization.admins.id'))",
      update:
        "isAuthenticated && (auth.id in data.ref('class.owner.id') || auth.id in data.ref('class.classAdmins.id') || auth.id in data.ref('class.organization.owner.id') || auth.id in data.ref('class.organization.admins.id'))",
    },
  },
} satisfies InstantRules;

export default rules;
