/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as BlockedIndexRouteImport } from './routes/blocked/index'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserBillingRouteImport } from './routes/user/billing'
import { Route as OrganizationsOrgLayoutRouteImport } from './routes/organizations/_orgLayout'
import { Route as ClassesClassesLayoutRouteImport } from './routes/classes/_classesLayout'
import { Route as OrganizationsOrgLayoutIndexRouteImport } from './routes/organizations/_orgLayout/index'
import { Route as JoinOrganizationIndexRouteImport } from './routes/join/organization/index'
import { Route as JoinClassIndexRouteImport } from './routes/join/class/index'
import { Route as ClassesClassesLayoutIndexRouteImport } from './routes/classes/_classesLayout/index'
import { Route as OrganizationsOrgLayoutOrgIdIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/index'
import { Route as ClassesClassesLayoutMembersIndexRouteImport } from './routes/classes/_classesLayout/members/index'
import { Route as ClassesClassesLayoutClassIdIndexRouteImport } from './routes/classes/_classesLayout/$classId/index'
import { Route as OrganizationsOrgLayoutOrgIdMembersIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/members/index'
import { Route as ClassesClassesLayoutClassIdTasksIndexRouteImport } from './routes/classes/_classesLayout/$classId/tasks/index'
import { Route as ClassesClassesLayoutClassIdReadingIndexRouteImport } from './routes/classes/_classesLayout/$classId/reading/index'
import { Route as ClassesClassesLayoutClassIdRandomToolsIndexRouteImport } from './routes/classes/_classesLayout/$classId/random-tools/index'
import { Route as ClassesClassesLayoutClassIdMembersIndexRouteImport } from './routes/classes/_classesLayout/$classId/members/index'
import { Route as ClassesClassesLayoutClassIdGradebookIndexRouteImport } from './routes/classes/_classesLayout/$classId/gradebook/index'
import { Route as ClassesClassesLayoutClassIdExpectationsIndexRouteImport } from './routes/classes/_classesLayout/$classId/expectations/index'
import { Route as ClassesClassesLayoutClassIdAttendanceIndexRouteImport } from './routes/classes/_classesLayout/$classId/attendance/index'
import { Route as ClassesClassesLayoutClassIdAssignmentsIndexRouteImport } from './routes/classes/_classesLayout/$classId/assignments/index'
import { Route as OrganizationsOrgLayoutOrgIdMembersTeachersIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/members/teachers/index'
import { Route as OrganizationsOrgLayoutOrgIdMembersStudentsIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/members/students/index'
import { Route as OrganizationsOrgLayoutOrgIdMembersInviteIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/members/invite/index'
import { Route as OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/members/guardians/index'
import { Route as OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/members/assistant-teachers/index'
import { Route as OrganizationsOrgLayoutOrgIdMembersAdminsIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/members/admins/index'
import { Route as OrganizationsOrgLayoutOrgIdMainSettingsIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/main/settings/index'
import { Route as OrganizationsOrgLayoutOrgIdMainDashboardIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/main/dashboard/index'
import { Route as OrganizationsOrgLayoutOrgIdMainClassesIndexRouteImport } from './routes/organizations/_orgLayout/$orgId/main/classes/index'
import { Route as ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRouteImport } from './routes/classes/_classesLayout/$classId/random-tools/randomizer/index'
import { Route as ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRouteImport } from './routes/classes/_classesLayout/$classId/random-tools/random-event/index'
import { Route as ClassesClassesLayoutClassIdRandomToolsAssignersIndexRouteImport } from './routes/classes/_classesLayout/$classId/random-tools/assigners/index'
import { Route as ClassesClassesLayoutClassIdMembersTeachersIndexRouteImport } from './routes/classes/_classesLayout/$classId/members/teachers/index'
import { Route as ClassesClassesLayoutClassIdMembersStudentsIndexRouteImport } from './routes/classes/_classesLayout/$classId/members/students/index'
import { Route as ClassesClassesLayoutClassIdMembersInviteIndexRouteImport } from './routes/classes/_classesLayout/$classId/members/invite/index'
import { Route as ClassesClassesLayoutClassIdMembersGuardiansIndexRouteImport } from './routes/classes/_classesLayout/$classId/members/guardians/index'
import { Route as ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRouteImport } from './routes/classes/_classesLayout/$classId/members/assistant-teachers/index'
import { Route as ClassesClassesLayoutClassIdMembersAdminsIndexRouteImport } from './routes/classes/_classesLayout/$classId/members/admins/index'
import { Route as ClassesClassesLayoutClassIdMainSettingsIndexRouteImport } from './routes/classes/_classesLayout/$classId/main/settings/index'
import { Route as ClassesClassesLayoutClassIdMainPointsIndexRouteImport } from './routes/classes/_classesLayout/$classId/main/points/index'
import { Route as ClassesClassesLayoutClassIdMainDashboardIndexRouteImport } from './routes/classes/_classesLayout/$classId/main/dashboard/index'
import { Route as ClassesClassesLayoutClassIdMainClassroomScreenIndexRouteImport } from './routes/classes/_classesLayout/$classId/main/classroom-screen/index'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedIndexRoute = BlockedIndexRouteImport.update({
  id: '/blocked/',
  path: '/blocked/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBillingRoute = UserBillingRouteImport.update({
  id: '/user/billing',
  path: '/user/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgLayoutRoute = OrganizationsOrgLayoutRouteImport.update({
  id: '/organizations/_orgLayout',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassesLayoutRoute = ClassesClassesLayoutRouteImport.update({
  id: '/classes/_classesLayout',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgLayoutIndexRoute =
  OrganizationsOrgLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const JoinOrganizationIndexRoute = JoinOrganizationIndexRouteImport.update({
  id: '/join/organization/',
  path: '/join/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinClassIndexRoute = JoinClassIndexRouteImport.update({
  id: '/join/class/',
  path: '/join/class/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassesLayoutIndexRoute =
  ClassesClassesLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdIndexRoute =
  OrganizationsOrgLayoutOrgIdIndexRouteImport.update({
    id: '/$orgId/',
    path: '/$orgId/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const ClassesClassesLayoutMembersIndexRoute =
  ClassesClassesLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdIndexRoute =
  ClassesClassesLayoutClassIdIndexRouteImport.update({
    id: '/$classId/',
    path: '/$classId/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMembersIndexRoute =
  OrganizationsOrgLayoutOrgIdMembersIndexRouteImport.update({
    id: '/$orgId/members/',
    path: '/$orgId/members/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdTasksIndexRoute =
  ClassesClassesLayoutClassIdTasksIndexRouteImport.update({
    id: '/$classId/tasks/',
    path: '/$classId/tasks/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdReadingIndexRoute =
  ClassesClassesLayoutClassIdReadingIndexRouteImport.update({
    id: '/$classId/reading/',
    path: '/$classId/reading/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdRandomToolsIndexRoute =
  ClassesClassesLayoutClassIdRandomToolsIndexRouteImport.update({
    id: '/$classId/random-tools/',
    path: '/$classId/random-tools/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMembersIndexRoute =
  ClassesClassesLayoutClassIdMembersIndexRouteImport.update({
    id: '/$classId/members/',
    path: '/$classId/members/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdGradebookIndexRoute =
  ClassesClassesLayoutClassIdGradebookIndexRouteImport.update({
    id: '/$classId/gradebook/',
    path: '/$classId/gradebook/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdExpectationsIndexRoute =
  ClassesClassesLayoutClassIdExpectationsIndexRouteImport.update({
    id: '/$classId/expectations/',
    path: '/$classId/expectations/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdAttendanceIndexRoute =
  ClassesClassesLayoutClassIdAttendanceIndexRouteImport.update({
    id: '/$classId/attendance/',
    path: '/$classId/attendance/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdAssignmentsIndexRoute =
  ClassesClassesLayoutClassIdAssignmentsIndexRouteImport.update({
    id: '/$classId/assignments/',
    path: '/$classId/assignments/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute =
  OrganizationsOrgLayoutOrgIdMembersTeachersIndexRouteImport.update({
    id: '/$orgId/members/teachers/',
    path: '/$orgId/members/teachers/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute =
  OrganizationsOrgLayoutOrgIdMembersStudentsIndexRouteImport.update({
    id: '/$orgId/members/students/',
    path: '/$orgId/members/students/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute =
  OrganizationsOrgLayoutOrgIdMembersInviteIndexRouteImport.update({
    id: '/$orgId/members/invite/',
    path: '/$orgId/members/invite/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute =
  OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRouteImport.update({
    id: '/$orgId/members/guardians/',
    path: '/$orgId/members/guardians/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute =
  OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRouteImport.update({
    id: '/$orgId/members/assistant-teachers/',
    path: '/$orgId/members/assistant-teachers/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute =
  OrganizationsOrgLayoutOrgIdMembersAdminsIndexRouteImport.update({
    id: '/$orgId/members/admins/',
    path: '/$orgId/members/admins/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute =
  OrganizationsOrgLayoutOrgIdMainSettingsIndexRouteImport.update({
    id: '/$orgId/main/settings/',
    path: '/$orgId/main/settings/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute =
  OrganizationsOrgLayoutOrgIdMainDashboardIndexRouteImport.update({
    id: '/$orgId/main/dashboard/',
    path: '/$orgId/main/dashboard/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdMainClassesIndexRoute =
  OrganizationsOrgLayoutOrgIdMainClassesIndexRouteImport.update({
    id: '/$orgId/main/classes/',
    path: '/$orgId/main/classes/',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute =
  ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRouteImport.update({
    id: '/$classId/random-tools/randomizer/',
    path: '/$classId/random-tools/randomizer/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute =
  ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRouteImport.update({
    id: '/$classId/random-tools/random-event/',
    path: '/$classId/random-tools/random-event/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute =
  ClassesClassesLayoutClassIdRandomToolsAssignersIndexRouteImport.update({
    id: '/$classId/random-tools/assigners/',
    path: '/$classId/random-tools/assigners/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMembersTeachersIndexRoute =
  ClassesClassesLayoutClassIdMembersTeachersIndexRouteImport.update({
    id: '/$classId/members/teachers/',
    path: '/$classId/members/teachers/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMembersStudentsIndexRoute =
  ClassesClassesLayoutClassIdMembersStudentsIndexRouteImport.update({
    id: '/$classId/members/students/',
    path: '/$classId/members/students/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMembersInviteIndexRoute =
  ClassesClassesLayoutClassIdMembersInviteIndexRouteImport.update({
    id: '/$classId/members/invite/',
    path: '/$classId/members/invite/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMembersGuardiansIndexRoute =
  ClassesClassesLayoutClassIdMembersGuardiansIndexRouteImport.update({
    id: '/$classId/members/guardians/',
    path: '/$classId/members/guardians/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute =
  ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRouteImport.update({
    id: '/$classId/members/assistant-teachers/',
    path: '/$classId/members/assistant-teachers/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMembersAdminsIndexRoute =
  ClassesClassesLayoutClassIdMembersAdminsIndexRouteImport.update({
    id: '/$classId/members/admins/',
    path: '/$classId/members/admins/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMainSettingsIndexRoute =
  ClassesClassesLayoutClassIdMainSettingsIndexRouteImport.update({
    id: '/$classId/main/settings/',
    path: '/$classId/main/settings/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMainPointsIndexRoute =
  ClassesClassesLayoutClassIdMainPointsIndexRouteImport.update({
    id: '/$classId/main/points/',
    path: '/$classId/main/points/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMainDashboardIndexRoute =
  ClassesClassesLayoutClassIdMainDashboardIndexRouteImport.update({
    id: '/$classId/main/dashboard/',
    path: '/$classId/main/dashboard/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute =
  ClassesClassesLayoutClassIdMainClassroomScreenIndexRouteImport.update({
    id: '/$classId/main/classroom-screen/',
    path: '/$classId/main/classroom-screen/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/classes': typeof ClassesClassesLayoutRouteWithChildren
  '/organizations': typeof OrganizationsOrgLayoutRouteWithChildren
  '/user/billing': typeof UserBillingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/blocked': typeof BlockedIndexRoute
  '/join': typeof JoinIndexRoute
  '/classes/': typeof ClassesClassesLayoutIndexRoute
  '/join/class': typeof JoinClassIndexRoute
  '/join/organization': typeof JoinOrganizationIndexRoute
  '/organizations/': typeof OrganizationsOrgLayoutIndexRoute
  '/classes/$classId': typeof ClassesClassesLayoutClassIdIndexRoute
  '/classes/members': typeof ClassesClassesLayoutMembersIndexRoute
  '/organizations/$orgId': typeof OrganizationsOrgLayoutOrgIdIndexRoute
  '/classes/$classId/assignments': typeof ClassesClassesLayoutClassIdAssignmentsIndexRoute
  '/classes/$classId/attendance': typeof ClassesClassesLayoutClassIdAttendanceIndexRoute
  '/classes/$classId/expectations': typeof ClassesClassesLayoutClassIdExpectationsIndexRoute
  '/classes/$classId/gradebook': typeof ClassesClassesLayoutClassIdGradebookIndexRoute
  '/classes/$classId/members': typeof ClassesClassesLayoutClassIdMembersIndexRoute
  '/classes/$classId/random-tools': typeof ClassesClassesLayoutClassIdRandomToolsIndexRoute
  '/classes/$classId/reading': typeof ClassesClassesLayoutClassIdReadingIndexRoute
  '/classes/$classId/tasks': typeof ClassesClassesLayoutClassIdTasksIndexRoute
  '/organizations/$orgId/members': typeof OrganizationsOrgLayoutOrgIdMembersIndexRoute
  '/classes/$classId/main/classroom-screen': typeof ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute
  '/classes/$classId/main/dashboard': typeof ClassesClassesLayoutClassIdMainDashboardIndexRoute
  '/classes/$classId/main/points': typeof ClassesClassesLayoutClassIdMainPointsIndexRoute
  '/classes/$classId/main/settings': typeof ClassesClassesLayoutClassIdMainSettingsIndexRoute
  '/classes/$classId/members/admins': typeof ClassesClassesLayoutClassIdMembersAdminsIndexRoute
  '/classes/$classId/members/assistant-teachers': typeof ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute
  '/classes/$classId/members/guardians': typeof ClassesClassesLayoutClassIdMembersGuardiansIndexRoute
  '/classes/$classId/members/invite': typeof ClassesClassesLayoutClassIdMembersInviteIndexRoute
  '/classes/$classId/members/students': typeof ClassesClassesLayoutClassIdMembersStudentsIndexRoute
  '/classes/$classId/members/teachers': typeof ClassesClassesLayoutClassIdMembersTeachersIndexRoute
  '/classes/$classId/random-tools/assigners': typeof ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute
  '/classes/$classId/random-tools/random-event': typeof ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute
  '/classes/$classId/random-tools/randomizer': typeof ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute
  '/organizations/$orgId/main/classes': typeof OrganizationsOrgLayoutOrgIdMainClassesIndexRoute
  '/organizations/$orgId/main/dashboard': typeof OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute
  '/organizations/$orgId/main/settings': typeof OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute
  '/organizations/$orgId/members/admins': typeof OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute
  '/organizations/$orgId/members/assistant-teachers': typeof OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute
  '/organizations/$orgId/members/guardians': typeof OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute
  '/organizations/$orgId/members/invite': typeof OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute
  '/organizations/$orgId/members/students': typeof OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute
  '/organizations/$orgId/members/teachers': typeof OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/user/billing': typeof UserBillingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/blocked': typeof BlockedIndexRoute
  '/join': typeof JoinIndexRoute
  '/classes': typeof ClassesClassesLayoutIndexRoute
  '/join/class': typeof JoinClassIndexRoute
  '/join/organization': typeof JoinOrganizationIndexRoute
  '/organizations': typeof OrganizationsOrgLayoutIndexRoute
  '/classes/$classId': typeof ClassesClassesLayoutClassIdIndexRoute
  '/classes/members': typeof ClassesClassesLayoutMembersIndexRoute
  '/organizations/$orgId': typeof OrganizationsOrgLayoutOrgIdIndexRoute
  '/classes/$classId/assignments': typeof ClassesClassesLayoutClassIdAssignmentsIndexRoute
  '/classes/$classId/attendance': typeof ClassesClassesLayoutClassIdAttendanceIndexRoute
  '/classes/$classId/expectations': typeof ClassesClassesLayoutClassIdExpectationsIndexRoute
  '/classes/$classId/gradebook': typeof ClassesClassesLayoutClassIdGradebookIndexRoute
  '/classes/$classId/members': typeof ClassesClassesLayoutClassIdMembersIndexRoute
  '/classes/$classId/random-tools': typeof ClassesClassesLayoutClassIdRandomToolsIndexRoute
  '/classes/$classId/reading': typeof ClassesClassesLayoutClassIdReadingIndexRoute
  '/classes/$classId/tasks': typeof ClassesClassesLayoutClassIdTasksIndexRoute
  '/organizations/$orgId/members': typeof OrganizationsOrgLayoutOrgIdMembersIndexRoute
  '/classes/$classId/main/classroom-screen': typeof ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute
  '/classes/$classId/main/dashboard': typeof ClassesClassesLayoutClassIdMainDashboardIndexRoute
  '/classes/$classId/main/points': typeof ClassesClassesLayoutClassIdMainPointsIndexRoute
  '/classes/$classId/main/settings': typeof ClassesClassesLayoutClassIdMainSettingsIndexRoute
  '/classes/$classId/members/admins': typeof ClassesClassesLayoutClassIdMembersAdminsIndexRoute
  '/classes/$classId/members/assistant-teachers': typeof ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute
  '/classes/$classId/members/guardians': typeof ClassesClassesLayoutClassIdMembersGuardiansIndexRoute
  '/classes/$classId/members/invite': typeof ClassesClassesLayoutClassIdMembersInviteIndexRoute
  '/classes/$classId/members/students': typeof ClassesClassesLayoutClassIdMembersStudentsIndexRoute
  '/classes/$classId/members/teachers': typeof ClassesClassesLayoutClassIdMembersTeachersIndexRoute
  '/classes/$classId/random-tools/assigners': typeof ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute
  '/classes/$classId/random-tools/random-event': typeof ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute
  '/classes/$classId/random-tools/randomizer': typeof ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute
  '/organizations/$orgId/main/classes': typeof OrganizationsOrgLayoutOrgIdMainClassesIndexRoute
  '/organizations/$orgId/main/dashboard': typeof OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute
  '/organizations/$orgId/main/settings': typeof OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute
  '/organizations/$orgId/members/admins': typeof OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute
  '/organizations/$orgId/members/assistant-teachers': typeof OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute
  '/organizations/$orgId/members/guardians': typeof OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute
  '/organizations/$orgId/members/invite': typeof OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute
  '/organizations/$orgId/members/students': typeof OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute
  '/organizations/$orgId/members/teachers': typeof OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/classes/_classesLayout': typeof ClassesClassesLayoutRouteWithChildren
  '/organizations/_orgLayout': typeof OrganizationsOrgLayoutRouteWithChildren
  '/user/billing': typeof UserBillingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/blocked/': typeof BlockedIndexRoute
  '/join/': typeof JoinIndexRoute
  '/classes/_classesLayout/': typeof ClassesClassesLayoutIndexRoute
  '/join/class/': typeof JoinClassIndexRoute
  '/join/organization/': typeof JoinOrganizationIndexRoute
  '/organizations/_orgLayout/': typeof OrganizationsOrgLayoutIndexRoute
  '/classes/_classesLayout/$classId/': typeof ClassesClassesLayoutClassIdIndexRoute
  '/classes/_classesLayout/members/': typeof ClassesClassesLayoutMembersIndexRoute
  '/organizations/_orgLayout/$orgId/': typeof OrganizationsOrgLayoutOrgIdIndexRoute
  '/classes/_classesLayout/$classId/assignments/': typeof ClassesClassesLayoutClassIdAssignmentsIndexRoute
  '/classes/_classesLayout/$classId/attendance/': typeof ClassesClassesLayoutClassIdAttendanceIndexRoute
  '/classes/_classesLayout/$classId/expectations/': typeof ClassesClassesLayoutClassIdExpectationsIndexRoute
  '/classes/_classesLayout/$classId/gradebook/': typeof ClassesClassesLayoutClassIdGradebookIndexRoute
  '/classes/_classesLayout/$classId/members/': typeof ClassesClassesLayoutClassIdMembersIndexRoute
  '/classes/_classesLayout/$classId/random-tools/': typeof ClassesClassesLayoutClassIdRandomToolsIndexRoute
  '/classes/_classesLayout/$classId/reading/': typeof ClassesClassesLayoutClassIdReadingIndexRoute
  '/classes/_classesLayout/$classId/tasks/': typeof ClassesClassesLayoutClassIdTasksIndexRoute
  '/organizations/_orgLayout/$orgId/members/': typeof OrganizationsOrgLayoutOrgIdMembersIndexRoute
  '/classes/_classesLayout/$classId/main/classroom-screen/': typeof ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute
  '/classes/_classesLayout/$classId/main/dashboard/': typeof ClassesClassesLayoutClassIdMainDashboardIndexRoute
  '/classes/_classesLayout/$classId/main/points/': typeof ClassesClassesLayoutClassIdMainPointsIndexRoute
  '/classes/_classesLayout/$classId/main/settings/': typeof ClassesClassesLayoutClassIdMainSettingsIndexRoute
  '/classes/_classesLayout/$classId/members/admins/': typeof ClassesClassesLayoutClassIdMembersAdminsIndexRoute
  '/classes/_classesLayout/$classId/members/assistant-teachers/': typeof ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute
  '/classes/_classesLayout/$classId/members/guardians/': typeof ClassesClassesLayoutClassIdMembersGuardiansIndexRoute
  '/classes/_classesLayout/$classId/members/invite/': typeof ClassesClassesLayoutClassIdMembersInviteIndexRoute
  '/classes/_classesLayout/$classId/members/students/': typeof ClassesClassesLayoutClassIdMembersStudentsIndexRoute
  '/classes/_classesLayout/$classId/members/teachers/': typeof ClassesClassesLayoutClassIdMembersTeachersIndexRoute
  '/classes/_classesLayout/$classId/random-tools/assigners/': typeof ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute
  '/classes/_classesLayout/$classId/random-tools/random-event/': typeof ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute
  '/classes/_classesLayout/$classId/random-tools/randomizer/': typeof ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute
  '/organizations/_orgLayout/$orgId/main/classes/': typeof OrganizationsOrgLayoutOrgIdMainClassesIndexRoute
  '/organizations/_orgLayout/$orgId/main/dashboard/': typeof OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute
  '/organizations/_orgLayout/$orgId/main/settings/': typeof OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute
  '/organizations/_orgLayout/$orgId/members/admins/': typeof OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute
  '/organizations/_orgLayout/$orgId/members/assistant-teachers/': typeof OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute
  '/organizations/_orgLayout/$orgId/members/guardians/': typeof OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute
  '/organizations/_orgLayout/$orgId/members/invite/': typeof OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute
  '/organizations/_orgLayout/$orgId/members/students/': typeof OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute
  '/organizations/_orgLayout/$orgId/members/teachers/': typeof OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/classes'
    | '/organizations'
    | '/user/billing'
    | '/user/profile'
    | '/user/settings'
    | '/blocked'
    | '/join'
    | '/classes/'
    | '/join/class'
    | '/join/organization'
    | '/organizations/'
    | '/classes/$classId'
    | '/classes/members'
    | '/organizations/$orgId'
    | '/classes/$classId/assignments'
    | '/classes/$classId/attendance'
    | '/classes/$classId/expectations'
    | '/classes/$classId/gradebook'
    | '/classes/$classId/members'
    | '/classes/$classId/random-tools'
    | '/classes/$classId/reading'
    | '/classes/$classId/tasks'
    | '/organizations/$orgId/members'
    | '/classes/$classId/main/classroom-screen'
    | '/classes/$classId/main/dashboard'
    | '/classes/$classId/main/points'
    | '/classes/$classId/main/settings'
    | '/classes/$classId/members/admins'
    | '/classes/$classId/members/assistant-teachers'
    | '/classes/$classId/members/guardians'
    | '/classes/$classId/members/invite'
    | '/classes/$classId/members/students'
    | '/classes/$classId/members/teachers'
    | '/classes/$classId/random-tools/assigners'
    | '/classes/$classId/random-tools/random-event'
    | '/classes/$classId/random-tools/randomizer'
    | '/organizations/$orgId/main/classes'
    | '/organizations/$orgId/main/dashboard'
    | '/organizations/$orgId/main/settings'
    | '/organizations/$orgId/members/admins'
    | '/organizations/$orgId/members/assistant-teachers'
    | '/organizations/$orgId/members/guardians'
    | '/organizations/$orgId/members/invite'
    | '/organizations/$orgId/members/students'
    | '/organizations/$orgId/members/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/user/billing'
    | '/user/profile'
    | '/user/settings'
    | '/blocked'
    | '/join'
    | '/classes'
    | '/join/class'
    | '/join/organization'
    | '/organizations'
    | '/classes/$classId'
    | '/classes/members'
    | '/organizations/$orgId'
    | '/classes/$classId/assignments'
    | '/classes/$classId/attendance'
    | '/classes/$classId/expectations'
    | '/classes/$classId/gradebook'
    | '/classes/$classId/members'
    | '/classes/$classId/random-tools'
    | '/classes/$classId/reading'
    | '/classes/$classId/tasks'
    | '/organizations/$orgId/members'
    | '/classes/$classId/main/classroom-screen'
    | '/classes/$classId/main/dashboard'
    | '/classes/$classId/main/points'
    | '/classes/$classId/main/settings'
    | '/classes/$classId/members/admins'
    | '/classes/$classId/members/assistant-teachers'
    | '/classes/$classId/members/guardians'
    | '/classes/$classId/members/invite'
    | '/classes/$classId/members/students'
    | '/classes/$classId/members/teachers'
    | '/classes/$classId/random-tools/assigners'
    | '/classes/$classId/random-tools/random-event'
    | '/classes/$classId/random-tools/randomizer'
    | '/organizations/$orgId/main/classes'
    | '/organizations/$orgId/main/dashboard'
    | '/organizations/$orgId/main/settings'
    | '/organizations/$orgId/members/admins'
    | '/organizations/$orgId/members/assistant-teachers'
    | '/organizations/$orgId/members/guardians'
    | '/organizations/$orgId/members/invite'
    | '/organizations/$orgId/members/students'
    | '/organizations/$orgId/members/teachers'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/classes/_classesLayout'
    | '/organizations/_orgLayout'
    | '/user/billing'
    | '/user/profile'
    | '/user/settings'
    | '/blocked/'
    | '/join/'
    | '/classes/_classesLayout/'
    | '/join/class/'
    | '/join/organization/'
    | '/organizations/_orgLayout/'
    | '/classes/_classesLayout/$classId/'
    | '/classes/_classesLayout/members/'
    | '/organizations/_orgLayout/$orgId/'
    | '/classes/_classesLayout/$classId/assignments/'
    | '/classes/_classesLayout/$classId/attendance/'
    | '/classes/_classesLayout/$classId/expectations/'
    | '/classes/_classesLayout/$classId/gradebook/'
    | '/classes/_classesLayout/$classId/members/'
    | '/classes/_classesLayout/$classId/random-tools/'
    | '/classes/_classesLayout/$classId/reading/'
    | '/classes/_classesLayout/$classId/tasks/'
    | '/organizations/_orgLayout/$orgId/members/'
    | '/classes/_classesLayout/$classId/main/classroom-screen/'
    | '/classes/_classesLayout/$classId/main/dashboard/'
    | '/classes/_classesLayout/$classId/main/points/'
    | '/classes/_classesLayout/$classId/main/settings/'
    | '/classes/_classesLayout/$classId/members/admins/'
    | '/classes/_classesLayout/$classId/members/assistant-teachers/'
    | '/classes/_classesLayout/$classId/members/guardians/'
    | '/classes/_classesLayout/$classId/members/invite/'
    | '/classes/_classesLayout/$classId/members/students/'
    | '/classes/_classesLayout/$classId/members/teachers/'
    | '/classes/_classesLayout/$classId/random-tools/assigners/'
    | '/classes/_classesLayout/$classId/random-tools/random-event/'
    | '/classes/_classesLayout/$classId/random-tools/randomizer/'
    | '/organizations/_orgLayout/$orgId/main/classes/'
    | '/organizations/_orgLayout/$orgId/main/dashboard/'
    | '/organizations/_orgLayout/$orgId/main/settings/'
    | '/organizations/_orgLayout/$orgId/members/admins/'
    | '/organizations/_orgLayout/$orgId/members/assistant-teachers/'
    | '/organizations/_orgLayout/$orgId/members/guardians/'
    | '/organizations/_orgLayout/$orgId/members/invite/'
    | '/organizations/_orgLayout/$orgId/members/students/'
    | '/organizations/_orgLayout/$orgId/members/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ClassesClassesLayoutRoute: typeof ClassesClassesLayoutRouteWithChildren
  OrganizationsOrgLayoutRoute: typeof OrganizationsOrgLayoutRouteWithChildren
  UserBillingRoute: typeof UserBillingRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSettingsRoute: typeof UserSettingsRoute
  BlockedIndexRoute: typeof BlockedIndexRoute
  JoinIndexRoute: typeof JoinIndexRoute
  JoinClassIndexRoute: typeof JoinClassIndexRoute
  JoinOrganizationIndexRoute: typeof JoinOrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked/': {
      id: '/blocked/'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/billing': {
      id: '/user/billing'
      path: '/user/billing'
      fullPath: '/user/billing'
      preLoaderRoute: typeof UserBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/_orgLayout': {
      id: '/organizations/_orgLayout'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsOrgLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/_classesLayout': {
      id: '/classes/_classesLayout'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesClassesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/_orgLayout/': {
      id: '/organizations/_orgLayout/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsOrgLayoutIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/join/organization/': {
      id: '/join/organization/'
      path: '/join/organization'
      fullPath: '/join/organization'
      preLoaderRoute: typeof JoinOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/class/': {
      id: '/join/class/'
      path: '/join/class'
      fullPath: '/join/class'
      preLoaderRoute: typeof JoinClassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/_classesLayout/': {
      id: '/classes/_classesLayout/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesClassesLayoutIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/': {
      id: '/organizations/_orgLayout/$orgId/'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/classes/_classesLayout/members/': {
      id: '/classes/_classesLayout/members/'
      path: '/members'
      fullPath: '/classes/members'
      preLoaderRoute: typeof ClassesClassesLayoutMembersIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/': {
      id: '/classes/_classesLayout/$classId/'
      path: '/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/members/': {
      id: '/organizations/_orgLayout/$orgId/members/'
      path: '/$orgId/members'
      fullPath: '/organizations/$orgId/members'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMembersIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/classes/_classesLayout/$classId/tasks/': {
      id: '/classes/_classesLayout/$classId/tasks/'
      path: '/$classId/tasks'
      fullPath: '/classes/$classId/tasks'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdTasksIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/reading/': {
      id: '/classes/_classesLayout/$classId/reading/'
      path: '/$classId/reading'
      fullPath: '/classes/$classId/reading'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdReadingIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/random-tools/': {
      id: '/classes/_classesLayout/$classId/random-tools/'
      path: '/$classId/random-tools'
      fullPath: '/classes/$classId/random-tools'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdRandomToolsIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/members/': {
      id: '/classes/_classesLayout/$classId/members/'
      path: '/$classId/members'
      fullPath: '/classes/$classId/members'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMembersIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/gradebook/': {
      id: '/classes/_classesLayout/$classId/gradebook/'
      path: '/$classId/gradebook'
      fullPath: '/classes/$classId/gradebook'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdGradebookIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/expectations/': {
      id: '/classes/_classesLayout/$classId/expectations/'
      path: '/$classId/expectations'
      fullPath: '/classes/$classId/expectations'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdExpectationsIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/attendance/': {
      id: '/classes/_classesLayout/$classId/attendance/'
      path: '/$classId/attendance'
      fullPath: '/classes/$classId/attendance'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdAttendanceIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/assignments/': {
      id: '/classes/_classesLayout/$classId/assignments/'
      path: '/$classId/assignments'
      fullPath: '/classes/$classId/assignments'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdAssignmentsIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/members/teachers/': {
      id: '/organizations/_orgLayout/$orgId/members/teachers/'
      path: '/$orgId/members/teachers'
      fullPath: '/organizations/$orgId/members/teachers'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMembersTeachersIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/members/students/': {
      id: '/organizations/_orgLayout/$orgId/members/students/'
      path: '/$orgId/members/students'
      fullPath: '/organizations/$orgId/members/students'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMembersStudentsIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/members/invite/': {
      id: '/organizations/_orgLayout/$orgId/members/invite/'
      path: '/$orgId/members/invite'
      fullPath: '/organizations/$orgId/members/invite'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMembersInviteIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/members/guardians/': {
      id: '/organizations/_orgLayout/$orgId/members/guardians/'
      path: '/$orgId/members/guardians'
      fullPath: '/organizations/$orgId/members/guardians'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/members/assistant-teachers/': {
      id: '/organizations/_orgLayout/$orgId/members/assistant-teachers/'
      path: '/$orgId/members/assistant-teachers'
      fullPath: '/organizations/$orgId/members/assistant-teachers'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/members/admins/': {
      id: '/organizations/_orgLayout/$orgId/members/admins/'
      path: '/$orgId/members/admins'
      fullPath: '/organizations/$orgId/members/admins'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMembersAdminsIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/main/settings/': {
      id: '/organizations/_orgLayout/$orgId/main/settings/'
      path: '/$orgId/main/settings'
      fullPath: '/organizations/$orgId/main/settings'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMainSettingsIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/main/dashboard/': {
      id: '/organizations/_orgLayout/$orgId/main/dashboard/'
      path: '/$orgId/main/dashboard'
      fullPath: '/organizations/$orgId/main/dashboard'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMainDashboardIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/organizations/_orgLayout/$orgId/main/classes/': {
      id: '/organizations/_orgLayout/$orgId/main/classes/'
      path: '/$orgId/main/classes'
      fullPath: '/organizations/$orgId/main/classes'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdMainClassesIndexRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/classes/_classesLayout/$classId/random-tools/randomizer/': {
      id: '/classes/_classesLayout/$classId/random-tools/randomizer/'
      path: '/$classId/random-tools/randomizer'
      fullPath: '/classes/$classId/random-tools/randomizer'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/random-tools/random-event/': {
      id: '/classes/_classesLayout/$classId/random-tools/random-event/'
      path: '/$classId/random-tools/random-event'
      fullPath: '/classes/$classId/random-tools/random-event'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/random-tools/assigners/': {
      id: '/classes/_classesLayout/$classId/random-tools/assigners/'
      path: '/$classId/random-tools/assigners'
      fullPath: '/classes/$classId/random-tools/assigners'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdRandomToolsAssignersIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/members/teachers/': {
      id: '/classes/_classesLayout/$classId/members/teachers/'
      path: '/$classId/members/teachers'
      fullPath: '/classes/$classId/members/teachers'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMembersTeachersIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/members/students/': {
      id: '/classes/_classesLayout/$classId/members/students/'
      path: '/$classId/members/students'
      fullPath: '/classes/$classId/members/students'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMembersStudentsIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/members/invite/': {
      id: '/classes/_classesLayout/$classId/members/invite/'
      path: '/$classId/members/invite'
      fullPath: '/classes/$classId/members/invite'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMembersInviteIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/members/guardians/': {
      id: '/classes/_classesLayout/$classId/members/guardians/'
      path: '/$classId/members/guardians'
      fullPath: '/classes/$classId/members/guardians'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMembersGuardiansIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/members/assistant-teachers/': {
      id: '/classes/_classesLayout/$classId/members/assistant-teachers/'
      path: '/$classId/members/assistant-teachers'
      fullPath: '/classes/$classId/members/assistant-teachers'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/members/admins/': {
      id: '/classes/_classesLayout/$classId/members/admins/'
      path: '/$classId/members/admins'
      fullPath: '/classes/$classId/members/admins'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMembersAdminsIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/main/settings/': {
      id: '/classes/_classesLayout/$classId/main/settings/'
      path: '/$classId/main/settings'
      fullPath: '/classes/$classId/main/settings'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMainSettingsIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/main/points/': {
      id: '/classes/_classesLayout/$classId/main/points/'
      path: '/$classId/main/points'
      fullPath: '/classes/$classId/main/points'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMainPointsIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/main/dashboard/': {
      id: '/classes/_classesLayout/$classId/main/dashboard/'
      path: '/$classId/main/dashboard'
      fullPath: '/classes/$classId/main/dashboard'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMainDashboardIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/classes/_classesLayout/$classId/main/classroom-screen/': {
      id: '/classes/_classesLayout/$classId/main/classroom-screen/'
      path: '/$classId/main/classroom-screen'
      fullPath: '/classes/$classId/main/classroom-screen'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdMainClassroomScreenIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
  }
}

interface ClassesClassesLayoutRouteChildren {
  ClassesClassesLayoutIndexRoute: typeof ClassesClassesLayoutIndexRoute
  ClassesClassesLayoutClassIdIndexRoute: typeof ClassesClassesLayoutClassIdIndexRoute
  ClassesClassesLayoutMembersIndexRoute: typeof ClassesClassesLayoutMembersIndexRoute
  ClassesClassesLayoutClassIdAssignmentsIndexRoute: typeof ClassesClassesLayoutClassIdAssignmentsIndexRoute
  ClassesClassesLayoutClassIdAttendanceIndexRoute: typeof ClassesClassesLayoutClassIdAttendanceIndexRoute
  ClassesClassesLayoutClassIdExpectationsIndexRoute: typeof ClassesClassesLayoutClassIdExpectationsIndexRoute
  ClassesClassesLayoutClassIdGradebookIndexRoute: typeof ClassesClassesLayoutClassIdGradebookIndexRoute
  ClassesClassesLayoutClassIdMembersIndexRoute: typeof ClassesClassesLayoutClassIdMembersIndexRoute
  ClassesClassesLayoutClassIdRandomToolsIndexRoute: typeof ClassesClassesLayoutClassIdRandomToolsIndexRoute
  ClassesClassesLayoutClassIdReadingIndexRoute: typeof ClassesClassesLayoutClassIdReadingIndexRoute
  ClassesClassesLayoutClassIdTasksIndexRoute: typeof ClassesClassesLayoutClassIdTasksIndexRoute
  ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute: typeof ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute
  ClassesClassesLayoutClassIdMainDashboardIndexRoute: typeof ClassesClassesLayoutClassIdMainDashboardIndexRoute
  ClassesClassesLayoutClassIdMainPointsIndexRoute: typeof ClassesClassesLayoutClassIdMainPointsIndexRoute
  ClassesClassesLayoutClassIdMainSettingsIndexRoute: typeof ClassesClassesLayoutClassIdMainSettingsIndexRoute
  ClassesClassesLayoutClassIdMembersAdminsIndexRoute: typeof ClassesClassesLayoutClassIdMembersAdminsIndexRoute
  ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute: typeof ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute
  ClassesClassesLayoutClassIdMembersGuardiansIndexRoute: typeof ClassesClassesLayoutClassIdMembersGuardiansIndexRoute
  ClassesClassesLayoutClassIdMembersInviteIndexRoute: typeof ClassesClassesLayoutClassIdMembersInviteIndexRoute
  ClassesClassesLayoutClassIdMembersStudentsIndexRoute: typeof ClassesClassesLayoutClassIdMembersStudentsIndexRoute
  ClassesClassesLayoutClassIdMembersTeachersIndexRoute: typeof ClassesClassesLayoutClassIdMembersTeachersIndexRoute
  ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute: typeof ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute
  ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute: typeof ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute
  ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute: typeof ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute
}

const ClassesClassesLayoutRouteChildren: ClassesClassesLayoutRouteChildren = {
  ClassesClassesLayoutIndexRoute: ClassesClassesLayoutIndexRoute,
  ClassesClassesLayoutClassIdIndexRoute: ClassesClassesLayoutClassIdIndexRoute,
  ClassesClassesLayoutMembersIndexRoute: ClassesClassesLayoutMembersIndexRoute,
  ClassesClassesLayoutClassIdAssignmentsIndexRoute:
    ClassesClassesLayoutClassIdAssignmentsIndexRoute,
  ClassesClassesLayoutClassIdAttendanceIndexRoute:
    ClassesClassesLayoutClassIdAttendanceIndexRoute,
  ClassesClassesLayoutClassIdExpectationsIndexRoute:
    ClassesClassesLayoutClassIdExpectationsIndexRoute,
  ClassesClassesLayoutClassIdGradebookIndexRoute:
    ClassesClassesLayoutClassIdGradebookIndexRoute,
  ClassesClassesLayoutClassIdMembersIndexRoute:
    ClassesClassesLayoutClassIdMembersIndexRoute,
  ClassesClassesLayoutClassIdRandomToolsIndexRoute:
    ClassesClassesLayoutClassIdRandomToolsIndexRoute,
  ClassesClassesLayoutClassIdReadingIndexRoute:
    ClassesClassesLayoutClassIdReadingIndexRoute,
  ClassesClassesLayoutClassIdTasksIndexRoute:
    ClassesClassesLayoutClassIdTasksIndexRoute,
  ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute:
    ClassesClassesLayoutClassIdMainClassroomScreenIndexRoute,
  ClassesClassesLayoutClassIdMainDashboardIndexRoute:
    ClassesClassesLayoutClassIdMainDashboardIndexRoute,
  ClassesClassesLayoutClassIdMainPointsIndexRoute:
    ClassesClassesLayoutClassIdMainPointsIndexRoute,
  ClassesClassesLayoutClassIdMainSettingsIndexRoute:
    ClassesClassesLayoutClassIdMainSettingsIndexRoute,
  ClassesClassesLayoutClassIdMembersAdminsIndexRoute:
    ClassesClassesLayoutClassIdMembersAdminsIndexRoute,
  ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute:
    ClassesClassesLayoutClassIdMembersAssistantTeachersIndexRoute,
  ClassesClassesLayoutClassIdMembersGuardiansIndexRoute:
    ClassesClassesLayoutClassIdMembersGuardiansIndexRoute,
  ClassesClassesLayoutClassIdMembersInviteIndexRoute:
    ClassesClassesLayoutClassIdMembersInviteIndexRoute,
  ClassesClassesLayoutClassIdMembersStudentsIndexRoute:
    ClassesClassesLayoutClassIdMembersStudentsIndexRoute,
  ClassesClassesLayoutClassIdMembersTeachersIndexRoute:
    ClassesClassesLayoutClassIdMembersTeachersIndexRoute,
  ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute:
    ClassesClassesLayoutClassIdRandomToolsAssignersIndexRoute,
  ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute:
    ClassesClassesLayoutClassIdRandomToolsRandomEventIndexRoute,
  ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute:
    ClassesClassesLayoutClassIdRandomToolsRandomizerIndexRoute,
}

const ClassesClassesLayoutRouteWithChildren =
  ClassesClassesLayoutRoute._addFileChildren(ClassesClassesLayoutRouteChildren)

interface OrganizationsOrgLayoutRouteChildren {
  OrganizationsOrgLayoutIndexRoute: typeof OrganizationsOrgLayoutIndexRoute
  OrganizationsOrgLayoutOrgIdIndexRoute: typeof OrganizationsOrgLayoutOrgIdIndexRoute
  OrganizationsOrgLayoutOrgIdMembersIndexRoute: typeof OrganizationsOrgLayoutOrgIdMembersIndexRoute
  OrganizationsOrgLayoutOrgIdMainClassesIndexRoute: typeof OrganizationsOrgLayoutOrgIdMainClassesIndexRoute
  OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute: typeof OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute
  OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute: typeof OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute
  OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute: typeof OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute
  OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute: typeof OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute
  OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute: typeof OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute
  OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute: typeof OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute
  OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute: typeof OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute
  OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute: typeof OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute
}

const OrganizationsOrgLayoutRouteChildren: OrganizationsOrgLayoutRouteChildren =
  {
    OrganizationsOrgLayoutIndexRoute: OrganizationsOrgLayoutIndexRoute,
    OrganizationsOrgLayoutOrgIdIndexRoute:
      OrganizationsOrgLayoutOrgIdIndexRoute,
    OrganizationsOrgLayoutOrgIdMembersIndexRoute:
      OrganizationsOrgLayoutOrgIdMembersIndexRoute,
    OrganizationsOrgLayoutOrgIdMainClassesIndexRoute:
      OrganizationsOrgLayoutOrgIdMainClassesIndexRoute,
    OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute:
      OrganizationsOrgLayoutOrgIdMainDashboardIndexRoute,
    OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute:
      OrganizationsOrgLayoutOrgIdMainSettingsIndexRoute,
    OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute:
      OrganizationsOrgLayoutOrgIdMembersAdminsIndexRoute,
    OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute:
      OrganizationsOrgLayoutOrgIdMembersAssistantTeachersIndexRoute,
    OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute:
      OrganizationsOrgLayoutOrgIdMembersGuardiansIndexRoute,
    OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute:
      OrganizationsOrgLayoutOrgIdMembersInviteIndexRoute,
    OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute:
      OrganizationsOrgLayoutOrgIdMembersStudentsIndexRoute,
    OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute:
      OrganizationsOrgLayoutOrgIdMembersTeachersIndexRoute,
  }

const OrganizationsOrgLayoutRouteWithChildren =
  OrganizationsOrgLayoutRoute._addFileChildren(
    OrganizationsOrgLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ClassesClassesLayoutRoute: ClassesClassesLayoutRouteWithChildren,
  OrganizationsOrgLayoutRoute: OrganizationsOrgLayoutRouteWithChildren,
  UserBillingRoute: UserBillingRoute,
  UserProfileRoute: UserProfileRoute,
  UserSettingsRoute: UserSettingsRoute,
  BlockedIndexRoute: BlockedIndexRoute,
  JoinIndexRoute: JoinIndexRoute,
  JoinClassIndexRoute: JoinClassIndexRoute,
  JoinOrganizationIndexRoute: JoinOrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
