/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserBillingRouteImport } from './routes/user/billing'
import { Route as OrganizationsOrgLayoutRouteImport } from './routes/organizations/_orgLayout'
import { Route as ClassesClassesLayoutRouteImport } from './routes/classes/_classesLayout'
import { Route as ClassesClassesLayoutIndexRouteImport } from './routes/classes/_classesLayout/index'
import { Route as OrganizationsOrgLayoutOrgIdRouteImport } from './routes/organizations/_orgLayout/$orgId'
import { Route as ClassesClassesLayoutClassIdRouteImport } from './routes/classes/_classesLayout/$classId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBillingRoute = UserBillingRouteImport.update({
  id: '/user/billing',
  path: '/user/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgLayoutRoute = OrganizationsOrgLayoutRouteImport.update({
  id: '/organizations/_orgLayout',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassesLayoutRoute = ClassesClassesLayoutRouteImport.update({
  id: '/classes/_classesLayout',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassesLayoutIndexRoute =
  ClassesClassesLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)
const OrganizationsOrgLayoutOrgIdRoute =
  OrganizationsOrgLayoutOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => OrganizationsOrgLayoutRoute,
  } as any)
const ClassesClassesLayoutClassIdRoute =
  ClassesClassesLayoutClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => ClassesClassesLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classes': typeof ClassesClassesLayoutRouteWithChildren
  '/organizations': typeof OrganizationsIndexRoute
  '/user/billing': typeof UserBillingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/classes/$classId': typeof ClassesClassesLayoutClassIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgLayoutOrgIdRoute
  '/classes/': typeof ClassesClassesLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/user/billing': typeof UserBillingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/classes/$classId': typeof ClassesClassesLayoutClassIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgLayoutOrgIdRoute
  '/classes': typeof ClassesClassesLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classes/_classesLayout': typeof ClassesClassesLayoutRouteWithChildren
  '/organizations/_orgLayout': typeof OrganizationsOrgLayoutRouteWithChildren
  '/user/billing': typeof UserBillingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/classes/_classesLayout/$classId': typeof ClassesClassesLayoutClassIdRoute
  '/organizations/_orgLayout/$orgId': typeof OrganizationsOrgLayoutOrgIdRoute
  '/classes/_classesLayout/': typeof ClassesClassesLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/classes'
    | '/organizations'
    | '/user/billing'
    | '/user/profile'
    | '/user/settings'
    | '/classes/$classId'
    | '/organizations/$orgId'
    | '/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/organizations'
    | '/user/billing'
    | '/user/profile'
    | '/user/settings'
    | '/classes/$classId'
    | '/organizations/$orgId'
    | '/classes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/classes/_classesLayout'
    | '/organizations/_orgLayout'
    | '/user/billing'
    | '/user/profile'
    | '/user/settings'
    | '/organizations/'
    | '/classes/_classesLayout/$classId'
    | '/organizations/_orgLayout/$orgId'
    | '/classes/_classesLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClassesClassesLayoutRoute: typeof ClassesClassesLayoutRouteWithChildren
  OrganizationsOrgLayoutRoute: typeof OrganizationsOrgLayoutRouteWithChildren
  UserBillingRoute: typeof UserBillingRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSettingsRoute: typeof UserSettingsRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/billing': {
      id: '/user/billing'
      path: '/user/billing'
      fullPath: '/user/billing'
      preLoaderRoute: typeof UserBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/_orgLayout': {
      id: '/organizations/_orgLayout'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsOrgLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/_classesLayout': {
      id: '/classes/_classesLayout'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesClassesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/_classesLayout/': {
      id: '/classes/_classesLayout/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesClassesLayoutIndexRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
    '/organizations/_orgLayout/$orgId': {
      id: '/organizations/_orgLayout/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgLayoutOrgIdRouteImport
      parentRoute: typeof OrganizationsOrgLayoutRoute
    }
    '/classes/_classesLayout/$classId': {
      id: '/classes/_classesLayout/$classId'
      path: '/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassesLayoutClassIdRouteImport
      parentRoute: typeof ClassesClassesLayoutRoute
    }
  }
}

interface ClassesClassesLayoutRouteChildren {
  ClassesClassesLayoutClassIdRoute: typeof ClassesClassesLayoutClassIdRoute
  ClassesClassesLayoutIndexRoute: typeof ClassesClassesLayoutIndexRoute
}

const ClassesClassesLayoutRouteChildren: ClassesClassesLayoutRouteChildren = {
  ClassesClassesLayoutClassIdRoute: ClassesClassesLayoutClassIdRoute,
  ClassesClassesLayoutIndexRoute: ClassesClassesLayoutIndexRoute,
}

const ClassesClassesLayoutRouteWithChildren =
  ClassesClassesLayoutRoute._addFileChildren(ClassesClassesLayoutRouteChildren)

interface OrganizationsOrgLayoutRouteChildren {
  OrganizationsOrgLayoutOrgIdRoute: typeof OrganizationsOrgLayoutOrgIdRoute
}

const OrganizationsOrgLayoutRouteChildren: OrganizationsOrgLayoutRouteChildren =
  {
    OrganizationsOrgLayoutOrgIdRoute: OrganizationsOrgLayoutOrgIdRoute,
  }

const OrganizationsOrgLayoutRouteWithChildren =
  OrganizationsOrgLayoutRoute._addFileChildren(
    OrganizationsOrgLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClassesClassesLayoutRoute: ClassesClassesLayoutRouteWithChildren,
  OrganizationsOrgLayoutRoute: OrganizationsOrgLayoutRouteWithChildren,
  UserBillingRoute: UserBillingRoute,
  UserProfileRoute: UserProfileRoute,
  UserSettingsRoute: UserSettingsRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
